const products = [
  {
    id: 1,
    name: "Wool Blend Coat",
    category: "outerwear",
    price: 320,
    badge: "Bestseller",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Camel","Black","Ivory"],
    image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
    description: "Italian wool oversized coat with structured tailoring and luxury interior lining. A statement piece crafted for the discerning wardrobe.",
    details: ["100% Italian Wool","Dry clean only","Structured silhouette","Interior silk lining","Made in Italy"]
  },
  {
    id: 2,
    name: "Minimal Sneakers",
    category: "footwear",
    price: 180,
    badge: "New",
    sizes: ["38","39","40","41","42","43","44"],
    colors: ["White","Black","Sand"],
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    description: "Clean low-profile sneakers designed for elevated everyday wear. Minimal detailing meets premium craftsmanship.",
    details: ["Premium leather upper","Cushioned insole","Rubber outsole","Hand-finished edges","Made in Portugal"]
  },
  {
    id: 3,
    name: "Leather Carry Bag",
    category: "accessories",
    price: 260,
    badge: "Limited",
    sizes: ["One Size"],
    colors: ["Tan","Black","Forest"],
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
    description: "Luxury leather bag inspired by Scandinavian minimalism. Refined hardware and a clean silhouette make this a forever piece.",
    details: ["Full-grain vegetable leather","Adjustable strap","Interior zip pocket","Brass hardware","Made in Denmark"]
  },
  {
    id: 4,
    name: "Relaxed Knitwear",
    category: "outerwear",
    price: 140,
    badge: null,
    sizes: ["XS","S","M","L","XL"],
    colors: ["Oat","Charcoal","Sage"],
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
    description: "Soft-touch knitwear designed for layered luxury styling. The relaxed silhouette complements both formal and casual looks.",
    details: ["80% Merino wool, 20% cashmere","Hand wash cold","Relaxed oversized fit","Ribbed trim","Ethically sourced"]
  },
  {
    id: 5,
    name: "Silk Shirt",
    category: "essentials",
    price: 195,
    badge: "New",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Cream","Navy","Blush"],
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
    description: "Pure silk shirt with a fluid drape and timeless collar. Elevates any outfit from boardroom to evening.",
    details: ["100% Mulberry silk","Dry clean recommended","Relaxed fit","Mother-of-pearl buttons","Made in France"]
  },
  {
    id: 6,
    name: "Tailored Trousers",
    category: "essentials",
    price: 210,
    badge: null,
    sizes: ["XS","S","M","L","XL"],
    colors: ["Slate","Beige","Black"],
    image: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
    description: "Precision-cut tailored trousers with a wide-leg silhouette and clean press. The essential foundation of a capsule wardrobe.",
    details: ["Italian wool blend","Dry clean only","Wide-leg cut","Side pockets","Made in Italy"]
  },
  {
    id: 7,
    name: "Suede Loafers",
    category: "footwear",
    price: 240,
    badge: "Bestseller",
    sizes: ["38","39","40","41","42","43","44"],
    colors: ["Cognac","Black","Taupe"],
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    description: "Classic penny loafers in premium suede. A heritage silhouette reimagined for the modern wardrobe.",
    details: ["Italian suede upper","Leather lining","Leather sole","Slip-on fit","Made in Italy"]
  },
  {
    id: 8,
    name: "Cashmere Scarf",
    category: "accessories",
    price: 120,
    badge: null,
    sizes: ["One Size"],
    colors: ["Camel","Ivory","Burgundy"],
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
    image2: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
    description: "Pure cashmere scarf in a generous length and weight. An everyday luxury that transforms any look.",
    details: ["100% Grade A cashmere","Dry clean recommended","200cm x 70cm","Fringed ends","Made in Scotland"]
  }
];
